// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dateTime.proto

package demo.grpc;

public interface DateTimeMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demo.grpc.DateTimeMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
